import Link from 'next/link';
import styles from './page.module.css';

export const metadata = {
  title: 'Terms of Service - Cliptopus',
};

export default function TermsOfService() {
  return (
    <div className={styles.container}>
      <h1>Terms of Service</h1>
      <p className={styles.updated}>Last updated: March 2026</p>

      <p>
        Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully before using
        Cliptopus (&ldquo;Service&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or
        &ldquo;our&rdquo;). By accessing or using the Service, you agree to be bound by
        these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By creating an account or using Cliptopus, you acknowledge that you have
        read, understood, and agree to be bound by these Terms, as well as our{' '}
        <Link href="/privacy">Privacy Policy</Link>. We may update these Terms from time
        to time, and your continued use of the Service constitutes acceptance of any
        changes.
      </p>

      <h2>2. Description of Service</h2>
      <p>Cliptopus is a video repurposing platform that allows users to:</p>
      <ul>
        <li>Import videos from YouTube via URL</li>
        <li>Convert horizontal video to vertical format suitable for short-form platforms</li>
        <li>Generate captions using automated transcription</li>
        <li>Export and publish processed videos to TikTok</li>
      </ul>
      <p>The Service is available through free and paid subscription tiers, each with different usage limits and features.</p>

      <h2>3. User Accounts and Responsibilities</h2>

      <h3>3.1 Account Creation</h3>
      <p>
        You must authenticate using GitHub OAuth to create an account. You agree to
        provide accurate information and to keep your account credentials secure. You are
        responsible for all activity that occurs under your account.
      </p>

      <h3>3.2 TikTok Authorization</h3>
      <p>
        To publish videos through Cliptopus, you must authorize the Service to
        access your TikTok account via TikTok OAuth. You may revoke this authorization
        at any time through your TikTok account settings or through the Cliptopus
        dashboard.
      </p>

      <h3>3.3 Account Security</h3>
      <p>
        You are responsible for maintaining the confidentiality of your account. You
        agree to notify us immediately of any unauthorized use of your account or any
        other breach of security.
      </p>

      <h2>4. Content Ownership</h2>

      <h3>4.1 Your Content</h3>
      <p>
        You retain all ownership rights to content you submit, upload, or process through
        the Service (&ldquo;User Content&rdquo;). Cliptopus does not claim
        ownership of your content.
      </p>

      <h3>4.2 License to Cliptopus</h3>
      <p>
        By using the Service, you grant Cliptopus a limited, non-exclusive,
        royalty-free license to process, transform, store, and transmit your content
        solely for the purpose of providing and operating the Service. This license
        exists only for as long as your content remains on our platform and terminates
        when you delete your content or your account.
      </p>

      <h3>4.3 Output Content</h3>
      <p>
        Processed videos, captions, and other outputs generated by the Service from your
        content remain your property. You are solely responsible for how you use and
        distribute these outputs.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Process or distribute content that you do not own or do not have the right to use, including copyrighted material belonging to third parties</li>
        <li>Process or distribute content that is illegal, harmful, threatening, abusive, harassing, defamatory, obscene, or otherwise objectionable</li>
        <li>Violate any applicable local, state, national, or international law or regulation</li>
        <li>Infringe on the intellectual property rights of any third party</li>
        <li>Upload or transmit viruses, malware, or other harmful code</li>
        <li>Attempt to gain unauthorized access to the Service, other accounts, or connected systems</li>
        <li>Use the Service for any purpose that violates the terms of YouTube, TikTok, or any other third-party platform</li>
        <li>Circumvent usage limits, watermarks, or other restrictions imposed by your subscription tier</li>
        <li>Resell, sublicense, or commercially redistribute the Service without written permission</li>
      </ul>
      <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>

      <h2>6. Third-Party Services</h2>
      <p>
        Cliptopus integrates with third-party services to provide its
        functionality. By using the Service, you acknowledge and agree that:
      </p>
      <ul>
        <li><strong>YouTube</strong>: You must comply with the YouTube Terms of Service when using content from YouTube. You are solely responsible for ensuring you have the right to repurpose any YouTube video you process through the Service.</li>
        <li><strong>TikTok</strong>: You must comply with the TikTok Terms of Service when publishing content to TikTok. Cliptopus acts on your behalf when posting to your TikTok account.</li>
        <li><strong>OpenAI</strong>: Audio from your videos is sent to OpenAI&apos;s Whisper API for transcription. This processing is subject to OpenAI&apos;s Usage Policies.</li>
      </ul>
      <p>
        Cliptopus is not responsible for the availability, accuracy, or practices
        of these third-party services.
      </p>

      <h2>7. Subscription Plans and Payment</h2>

      <h3>7.1 Free Tier</h3>
      <p>
        The free tier includes up to 3 video exports per month. Exported videos on the
        free tier include a Cliptopus watermark.
      </p>

      <h3>7.2 Paid Tiers</h3>
      <p>
        Paid subscription plans are available at $15/month and $30/month, each offering
        increased export limits and additional features, including watermark-free
        exports.
      </p>

      <h3>7.3 Billing</h3>
      <p>
        Paid subscriptions are billed monthly. By subscribing to a paid plan, you
        authorize us to charge your selected payment method on a recurring basis until
        you cancel.
      </p>

      <h3>7.4 Cancellation and Refunds</h3>
      <p>
        You may cancel your subscription at any time. Cancellation takes effect at the
        end of the current billing period, and you will retain access to paid features
        until that time. We do not provide prorated refunds for partial billing periods.
      </p>

      <h3>7.5 Price Changes</h3>
      <p>
        We reserve the right to change subscription pricing. We will provide reasonable
        advance notice of any price changes, and they will take effect at the start of
        your next billing period.
      </p>

      <h2>8. Service Availability</h2>
      <p>
        We strive to maintain high availability of the Service, but we do not guarantee
        uninterrupted or error-free operation. The Service may be temporarily unavailable
        due to maintenance, updates, or circumstances beyond our control.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;
        WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT
        LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CLIPTOPUS SHALL NOT BE
        LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE
        SERVICE.
      </p>
      <p>
        IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT YOU HAVE PAID US IN THE
        TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER
        IS GREATER.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless Cliptopus and its
        operators from any claims, damages, losses, liabilities, and expenses arising out
        of or related to your use of the Service, your violation of these Terms, or your
        violation of any rights of a third party.
      </p>

      <h2>12. Termination</h2>
      <p>
        You may terminate your account at any time. We may suspend or terminate your
        access for conduct that violates these Terms. Upon termination, your right to use
        the Service will immediately cease and we may delete your account data.
      </p>

      <h2>13. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. We will notify users of
        material changes by posting the updated Terms on our website and updating the
        &ldquo;Last updated&rdquo; date.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with applicable law,
        without regard to conflict of law principles.
      </p>

      <h2>15. Severability</h2>
      <p>
        If any provision of these Terms is found to be unenforceable or invalid, that
        provision will be limited or eliminated to the minimum extent necessary so that
        the remaining Terms will remain in full force and effect.
      </p>

      <h2>16. Contact Information</h2>
      <p>
        If you have any questions about these Terms of Service, please contact us at:
      </p>
      <p><strong>Email</strong>: legal@cliptopus.com</p>
    </div>
  );
}
